### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by grossie** [camhart/ultimatetraffic#4]
Phase 0
- Very few cars are given/not given go command when they should/shouldn't receive it. i.e. Car 1 on current (March 21) code at iteration 500 is given the go command at the stop light. It is the only one of the group. Same with car 10 around then, he just sits stopped at the red light.
- Cars do not seem to keep distance between each other at stops according to the GUI (This may be due to the scaling of the GUI but if not, they sit right on top of one another.

Phase 1
-Some cars are still running red lights
-A small amount are running over other cars
-Same issue as above with cars on top of one another travelling similar speeds

With current (March 21) code, Phase 0 gets one extra car out by the end of a 10000 iteration run than Phase 1.

**Comment by camhart** [comment]
I think it'd probably be best to break each bug into a separate issue.  "Phase 0 gets one extra car out by the end of a 10000 iteration run than Phase 1" isn't necessarily a bug.  There is nothing to guarantee cars will finish by a certain iteration.  I did make it so if we set the iteration parameter to 0 it will run until all cars finish.  Although one would think Phase 1 would be faster at getting cars through than phase 0.
