### ISSUE TITLE
Phase 1 - Cars hit light perfectly, but on top of each other

### ISSUE THREAD

**Issue by camhart** [camhart/ultimatetraffic#6]
Cars will all time the light so they're in the same position (just about to cross from one light to the next).  When this happens the cars are on top of each other.

Potential fix...  Have each light keep track of the number of cars that are "perfectly timing" the red light.  For each one, set the distance the cars can reach back by 7 meters or something.

**Comment by camhart** [comment]
Brian

**Comment by urrry1** [comment]
I'm not 100% sure, but it looks like the getNextCar() function is either returning the wrong car or it's at least inconsistent.  As far as I can tell, the first few cars to run over the successive car check if they'll hit the next car, but the getNextCar() function returns itself, which it should only do if there is no car ahead.  I have suspicions that function is also the reason some cars randomly go way slowly, which would happen if getNextCar() occasionally returned a car behind the current car.

**Comment by urrry1** [comment]
getNextCar() works fine now.  We may want to adjust it later to change the time delay between cars so they don't get so close when moving extremely slow, but as is will work.
